name: marcocheung
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: grid-testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8ba4b4'
    - '#436676'
    - '#6a8a9c'
    - '#0a222f'
    - '#b4c6d3'
  brandStrength: 0
  lightness: 0.37462607654742897
  saturation: 0.611302470555529
  rhythmicContrast: 0.7989300698973238
purpose: []
